import type { VM } from '@/types/vmware';

// Sample VM data
export const sampleVMs: VM[] = [
  {
    id: 'vm-001',
    name: 'web-prod-01',
    description: 'Production web server for main application',
    status: 'running',
    type: 'server',
    ip: '10.0.1.10',
    cpu: 4,
    memory: 8,
    storage: 100,
    network: '1 Gbps',
    os: 'Ubuntu 24.04 LTS',
    createdAt: new Date('2025-01-10T10:30:00'),
    lastModified: new Date('2025-03-12T14:15:00'),
    powerState: 'poweredOn',
    hostServer: 'esx01.example.com',
    resourcePool: 'Production',
    datastorePath: '[datastore1] web-prod-01/',
    performanceMetrics: {
      cpuUsage: 65,
      memoryUsage: 72,
      diskIops: 120,
      networkThroughput: 35,
    },
    tags: ['prod', 'web', 'public-facing'],
    notes:
      'Handles main website traffic. Scheduled maintenance every third Sunday.',
  },
  {
    id: 'vm-002',
    name: 'db-prod-01',
    description: 'Production database server for primary application',
    status: 'running',
    type: 'database',
    ip: '10.0.1.20',
    cpu: 8,
    memory: 32,
    storage: 500,
    network: '10 Gbps',
    os: 'Red Hat Enterprise Linux 9',
    createdAt: new Date('2025-01-05T09:45:00'),
    lastModified: new Date('2025-03-10T11:30:00'),
    powerState: 'poweredOn',
    hostServer: 'esx02.example.com',
    resourcePool: 'Production',
    datastorePath: '[datastore2] db-prod-01/',
    performanceMetrics: {
      cpuUsage: 78,
      memoryUsage: 85,
      diskIops: 450,
      networkThroughput: 48,
    },
    tags: ['prod', 'database', 'critical'],
    notes: 'Primary PostgreSQL database instance. Backup every 4 hours.',
  },
  {
    id: 'vm-003',
    name: 'app-dev-01',
    description: 'Development server for application testing',
    status: 'running',
    type: 'server',
    ip: '10.0.2.10',
    cpu: 2,
    memory: 4,
    storage: 80,
    network: '1 Gbps',
    os: 'Ubuntu 24.04 LTS',
    createdAt: new Date('2025-01-20T13:15:00'),
    lastModified: new Date('2025-03-08T10:45:00'),
    powerState: 'poweredOn',
    hostServer: 'esx03.example.com',
    resourcePool: 'Development',
    datastorePath: '[datastore1] app-dev-01/',
    performanceMetrics: {
      cpuUsage: 25,
      memoryUsage: 40,
      diskIops: 30,
      networkThroughput: 12,
    },
    tags: ['dev', 'app'],
    notes: '',
  },
  {
    id: 'vm-004',
    name: 'win-vdi-01',
    description: 'Windows VDI for remote access',
    status: 'running',
    type: 'desktop',
    ip: '10.0.3.15',
    cpu: 2,
    memory: 8,
    storage: 120,
    network: '1 Gbps',
    os: 'Windows 11 Pro',
    createdAt: new Date('2025-02-10T11:00:00'),
    lastModified: new Date('2025-03-15T09:30:00'),
    powerState: 'poweredOn',
    hostServer: 'esx01.example.com',
    resourcePool: 'Desktop',
    datastorePath: '[datastore3] win-vdi-01/',
    performanceMetrics: {
      cpuUsage: 35,
      memoryUsage: 60,
      diskIops: 25,
      networkThroughput: 18,
    },
    tags: ['vdi', 'windows'],
    notes: 'Used by marketing team for remote work.',
  },
  {
    id: 'vm-005',
    name: 'db-test-01',
    description: 'Testing database for QA team',
    status: 'stopped',
    type: 'database',
    ip: '—',
    cpu: 4,
    memory: 16,
    storage: 250,
    network: '1 Gbps',
    os: 'Red Hat Enterprise Linux 9',
    createdAt: new Date('2025-02-15T14:30:00'),
    lastModified: new Date('2025-03-14T16:45:00'),
    powerState: 'poweredOff',
    hostServer: 'esx02.example.com',
    resourcePool: 'Testing',
    datastorePath: '[datastore2] db-test-01/',
    performanceMetrics: {
      cpuUsage: 0,
      memoryUsage: 0,
      diskIops: 0,
      networkThroughput: 0,
    },
    tags: ['test', 'database'],
    notes: 'Used for application testing. Contains anonymized production data.',
  },
  {
    id: 'vm-006',
    name: 'ci-jenkins-01',
    description: 'Jenkins CI/CD server',
    status: 'running',
    type: 'server',
    ip: '10.0.2.25',
    cpu: 4,
    memory: 8,
    storage: 120,
    network: '1 Gbps',
    os: 'Debian 12',
    createdAt: new Date('2025-01-25T10:15:00'),
    lastModified: new Date('2025-03-05T11:30:00'),
    powerState: 'poweredOn',
    hostServer: 'esx03.example.com',
    resourcePool: 'Development',
    datastorePath: '[datastore1] ci-jenkins-01/',
    performanceMetrics: {
      cpuUsage: 45,
      memoryUsage: 62,
      diskIops: 80,
      networkThroughput: 25,
    },
    tags: ['dev', 'ci', 'jenkins'],
    notes: 'Main CI/CD server for all projects.',
  },
  {
    id: 'vm-007',
    name: 'web-prod-02',
    description: 'Production web server (redundant)',
    status: 'maintenance',
    type: 'server',
    ip: '10.0.1.11',
    cpu: 4,
    memory: 8,
    storage: 100,
    network: '1 Gbps',
    os: 'Ubuntu 24.04 LTS',
    createdAt: new Date('2025-01-11T11:45:00'),
    lastModified: new Date('2025-03-16T08:30:00'),
    powerState: 'poweredOn',
    hostServer: 'esx01.example.com',
    resourcePool: 'Production',
    datastorePath: '[datastore1] web-prod-02/',
    performanceMetrics: {
      cpuUsage: 5,
      memoryUsage: 35,
      diskIops: 10,
      networkThroughput: 2,
    },
    tags: ['prod', 'web', 'public-facing'],
    notes: 'Under maintenance for security patches.',
  },
  {
    id: 'vm-008',
    name: 'win-vdi-02',
    description: 'Windows VDI for design team',
    status: 'suspended',
    type: 'desktop',
    ip: '10.0.3.16',
    cpu: 4,
    memory: 16,
    storage: 250,
    network: '1 Gbps',
    os: 'Windows 11 Pro',
    createdAt: new Date('2025-02-12T13:30:00'),
    lastModified: new Date('2025-03-15T17:30:00'),
    powerState: 'suspended',
    hostServer: 'esx04.example.com',
    resourcePool: 'Desktop',
    datastorePath: '[datastore3] win-vdi-02/',
    performanceMetrics: {
      cpuUsage: 0,
      memoryUsage: 0,
      diskIops: 0,
      networkThroughput: 0,
    },
    tags: ['vdi', 'windows', 'graphics'],
    notes: 'Used by design team. Higher resources for graphic work.',
  },
  {
    id: 'vm-009',
    name: 'cache-redis-01',
    description: 'Redis cache server for web applications',
    status: 'running',
    type: 'server',
    ip: '10.0.1.30',
    cpu: 2,
    memory: 8,
    storage: 50,
    network: '1 Gbps',
    os: 'Debian 12',
    createdAt: new Date('2025-02-20T09:15:00'),
    lastModified: new Date('2025-03-01T14:30:00'),
    powerState: 'poweredOn',
    hostServer: 'esx02.example.com',
    resourcePool: 'Production',
    datastorePath: '[datastore2] cache-redis-01/',
    performanceMetrics: {
      cpuUsage: 30,
      memoryUsage: 70,
      diskIops: 150,
      networkThroughput: 20,
    },
    tags: ['prod', 'cache', 'redis'],
    notes: '',
  },
  {
    id: 'vm-010',
    name: 'monitoring-01',
    description: 'Monitoring server for infrastructure',
    status: 'error',
    type: 'server',
    ip: '10.0.1.50',
    cpu: 2,
    memory: 4,
    storage: 80,
    network: '1 Gbps',
    os: 'Ubuntu 24.04 LTS',
    createdAt: new Date('2025-01-30T08:30:00'),
    lastModified: new Date('2025-03-17T07:15:00'),
    powerState: 'poweredOn',
    hostServer: 'esx03.example.com',
    resourcePool: 'Production',
    datastorePath: '[datastore1] monitoring-01/',
    performanceMetrics: {
      cpuUsage: 95,
      memoryUsage: 92,
      diskIops: 5,
      networkThroughput: 2,
    },
    tags: ['prod', 'monitoring'],
    notes: 'Critical error: Disk space near full. Needs immediate attention.',
  },
];
